version: '3.4'

services:
  posts:
    image: posts
    build:
      context: posts
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
